version: '3'
services:
  iq-server:
    #build: iq-server
    volumes:
      - ~/iq-data:/sonatype-work
    ports:
      - "8070:8070"
      - "8071:8071"
    image: sonatype/nexus-iq-server:1.42
    container_name: iq-server
  nexus:
    #build: nexus
    volumes:
      - ~/nexus-data:/nexus-data
      - ~/nexus-ssl:/opt/sonatype/nexus/etc/ssl
    ports:
      - "8081:8081"
      - "8443:8443"
      - "18443:18443"
      - "5000:5000"
    image: bradbeck/nexus-https:3.7
    links:
      - iq-server
    container_name: nexus3